server:
  port: 8081
spring:
  application:
    name: Student-Data-Management
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Student-Data-Management
  mail:
    host: smtp.gmail.com
    port: 587
    username: shekhawatsingharjun12345@gmail.com
    password: ykza vnle uugs cybm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
